export const MEDICAL_COLLEGES = [
  "AIIMS Telangana",
  "Osmania Medical College",
  "Gandhi Medical College, Secunderabad",
  "Kakatiya Medical College, Warangal",
  "Rajiv Gandhi Institute of Medical Sciences, Adilabad",
  "Govt Medical College, Nizamabad",
  "Govt Medical College, Mahabubnagar",
  "Govt Medical College, Siddipet",
  "Govt Medical College, Nalgonda",
  "Govt Medical College, Suryapet",
  "Govt Medical College, Jangaon",
  "Govt Medical College, Jayashankar Bhupalpally",
  "Govt Medical College, Kamareddy",
  "Govt Medical College, Karimnagar",
  "Govt Medical College, Khammam",
  "Govt Medical College, Kumuram Bheem Asifabad",
  "Govt Medical College, Nirmal",
  "Govt Medical College, Rajanna Sircilla",
  "Govt Medical College, Vikarabad",
  "Govt Medical College, Mancherial",
  "Govt Medical College, Ramagundam",
  "Govt Medical College, Jagtial",
  "Govt Medical College, Mahabubabad",
  "Govt Medical College, Kothagudem",
  "Govt Medical College, Sangareddy",
  "Govt Medical College, Wanaparthy",
  "Govt Medical College, Nagarkurnool",
  "Govt Medical College, Jogulamba Gadwal",
  "Govt Medical College, Mulugu",
  "Govt Medical College, Narayanpet",
  "Govt Medical College, Narsampet",
  "Govt Medical College, Maheshwaram",
  "Govt Medical College, Medak",
  "Govt Medical College, Quthbullapur",
  "Govt Medical College, Yadadri",
  "Govt Medical College, Kodangal",
  "ESIC Medical College, Hyderabad",
  "Nizam Institute of Medical Sciences, Hyderabad",
  "Mamata Medical College, Khammam",
  "SVS Medical College, Mahabubnagar",
  "Kamineni Institute of Medical Sciences, Narketpally",
  "MediCiti Institute of Medical Sciences",
  "Prathima Institute of Medical Sciences, Karimnagar",
  "MNR Medical College, Sangareddy",
  "Chalmeda Anand Rao Institute of Medical Sciences, Karimnagar",
  "Bhaskar Medical College",
  "Apollo Institute of Medical Sciences, Hyderabad",
  "Kamineni Academy of Medical Sciences, Hyderabad",
  "Mahavir Institute of Medical Sciences",
  "RVM Institute of Medical Sciences, Siddipet",
  "Mamata Academy of Medical Sciences, Bachupally",
  "Patnam Mahender Reddy Institute of Medical Sciences",
  "Surabhi Institute of Medical Sciences, Siddipet",
  "Maheshwara Medical College",
  "TRR Institute of Medical Sciences, Sangareddy",
  "Arundathi Institute of Medical Sciences",
  "CMR Institute of Medical Science",
  "Father Colombo Institute of Medical Sciences, Warangal",
  "Neelima Institute of Medical Sciences",
  "Prathima Relief Institute of Medical Sciences",
  "NOVA Institute of Medical Sciences",
  "Deccan College of Medical Sciences, Hyderabad",
  "Shadan Institute of Medical Sciences, Hyderabad",
  "Dr VRK Women's Medical College",
  "Ayaan Institute of Medical Sciences",
  "Malla Reddy Institute of Medical Sciences, Hyderabad",
  "Malla Reddy Medical College for Women, Hyderabad"
].sort();
